### PR TITLE
Change: Build Audio and Board references as hero

### PR DESCRIPTION
**Pull request by Tilix4**
## Changelog Description
It's been decided with anim and layout teams that Audio and Board References must be loaded as hero to avoid having to update by hand if a new version has been published.

## Testing notes:
1. Merge on last release
2. Build `e666_sh005` layout
3. Publish layout and camera
4. Build anim

### CODE REVIEW

**Comment by Sharkitty** [comment]
It works for me in layout but in anim I only get the audio ref, not the board ref.

**Comment by Tilix4** [comment]
Can you tell me on which you've tested? If it works on layout it should work on anim

**Comment by Sharkitty** [comment]
e108 sh034 and 035, e104 sh034 035

**Comment by Tilix4** [comment]
That's because the layout has been published already and I forgot the `BoardReference` is loaded in the anim using the loaded camera.

To test accurately, you should:
1. Build a layout with a camera
2. Publish layout and camera
3. Build anim

**Review by Sharkitty — APPROVED** [review]
Works now, LGTM

**Pull request merged**
